language: node_js
node_js:
- stable
cache:
  yarn: true
script: yarn test
before_deploy: yarn build:production
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: css-in-js-playground.com
  local-dir: dist
  acl: public_read_write
  detect_encoding: true
  on:
    branch: master
